config_version = 1
# Name of this device preset, used for lookup
name = "adafruit_si7021"
# Type of this preset; currently the only type is device
type = "device"

# Preset-level metadata; format follows that specified in the top-level
[metadata]
name_full = "Adafruit Si7021 Temp and Humidity Sensor"
author = "C.A.M. Gerlach"
description = "Device preset for reading the Adafruit Si7021 I2C Temp/Humidity sensor"
homepage = "https://www.Gerlach.CAM"
repo = "https://github.com/CAM-Gerlach"
preset_version = "0.1.0"
brokkr_version_min = "0.3.0"

# Data types referenced in individual presets
[data_types]
si7021_temperature = { full_name = "Temperature (Si7021)", binary_type = "f", unit = "C", uncertainty = 0.4, custom_attrs.attribute_name = "temperature", digits = 3, range_min = -10, range_max = 85 }
si7021_humidity = { full_name = "Humidity (Si7021)", binary_type = "f", unit = "%", uncertainty = 3.0, custom_attrs.attribute_name = "relative_humidity", digits = 3, range_min = 0, range_max = 80 }

# The Adafruit Si7021 data input
[inputs.si7021]
_module_path = "brokkr.inputs.adafruiti2c"
_class_name = "AdafruitPersistantI2CInput"
# Dependencies required by this specific input preset
_dependencies = [ "adafruit-circuitpython-si7021" ]
name = "Si7021 Temp & Humidity Sensor"
sensor_module = "adafruit_si7021"
sensor_class = "SI7021"
data_types = [
    "si7021_temperature",
    "si7021_humidity",
]
