config_version = 1
# Name of this device preset, used for lookup
name = "adafruit_htu21d"
# Type of this preset; currently the only type is device
type = "device"

# Preset-level metadata; format follows that specified in the top-level
[metadata]
name_full = "Adafruit HTU21D Temp and Humidity Sensor"
author = "C.A.M. Gerlach"
description = "Device preset for reading the Adafruit HTU21D I2C Temp/Humidity sensor"
homepage = "https://www.Gerlach.CAM"
repo = "https://github.com/CAM-Gerlach"
preset_version = "0.1.0"
brokkr_version_min = "0.3.0"

# Data types referenced in individual presets
[data_types]
htu21d_temperature = { full_name = "Temperature (HTU21D)", binary_type = "f", unit = "C", uncertainty = 1.0, custom_attrs.attribute_name = "temperature", digits = 3, range_min = -30, range_max = 90 }
htu21d_humidity = { full_name = "Humidity (HTU21D)", binary_type = "f", unit = "%", uncertainty = 2.0, custom_attrs.attribute_name = "relative_humidity", digits = 3, range_min = 5, range_max = 95 }

# The main Adafruit HTU21D data input
[inputs.htu21d]
_module_path = "brokkr.inputs.adafruiti2c"
_class_name = "AdafruitI2CInput"
# Dependencies required by this specific input preset
_dependencies = [ "adafruit-circuitpython-HTU21D" ]
name = "HTU21DF Temp & Humidity Sensor"
sensor_module = "adafruit_htu21d"
sensor_class = "HTU21D"
data_types = [
    "htu21d_temperature",
    "htu21d_humidity",
]
