config_version = 1
# Name of this device preset, used for lookup
name = "adafruit_dht"
# Type of this preset; currently the only type is device
type = "device"
# Dependencies required by all inputs in this device preset
_dependencies = [ "adafruit-circuitpython-dht" ]

# Preset-level metadata; format follows that specified in the top-level
[metadata]
name_full = "Adafruit DHTxx Temp and Humidity Sensors"
author = "C.A.M. Gerlach"
description = "Device preset for reading the AAdafruit DHTxx (DHTI2C Temp/Humidity sensor"
homepage = "https://www.Gerlach.CAM"
repo = "https://github.com/CAM-Gerlach"
preset_version = "0.1.0"
brokkr_version_min = "0.3.0"

[type_presets]
dht_temperature = { binary_type = "f", unit = "C", custom_attrs.attribute_name = "temperature", digits = 3 }
dht_humidity = { binary_type = "f", unit = "%", custom_attrs.attribute_name = "humidity", digits = 3 }

# Data types referenced in individual presets
[data_types]
dht11_temperature = { type_presets = "dht_temperature", full_name = "Temperature (DHT11)", uncertainty = 2.0, range_min = 0, range_max = 50 }
dht11_humidity = { type_presets = "dht_humidity", full_name = "Humidity (DHT11)", uncertainty = 5.0, range_min = 20, range_max = 80 }
dht22_temperature = {  type_presets = "dht_temperature", full_name = "Temperature (DHT22)", uncertainty = 0.5, range_min = -40, range_max = 80 }
dht22_humidity = { type_presets = "dht_humidity", full_name = "Humidity (DHT22)", uncertainty = 2.0, range_min = 0, range_max = 100 }

# Adafruit DHT11 data input
[inputs.dht11]
_module_path = "brokkr.inputs.adafruitonewire"
_class_name = "AdafruitOnewireInput"
_dependencies = []
name = "DHT11 Temp & Humidity Sensor"
sensor_module = "adafruit_dht"
sensor_class = "DHT11"
data_types = [
    "dht11_temperature",
    "dht11_humidity",
]

# Adafruit DHT22 data input
[inputs.dht22]
_module_path = "brokkr.inputs.adafruitonewire"
_class_name = "AdafruitOnewireInput"
_dependencies = []
name = "DHT22 Temp & Humidity Sensor"
sensor_module = "adafruit_dht"
sensor_class = "DHT22"
data_types = [
    "dht22_temperature",
    "dht22_humidity",
]
