config_version = 1
# Name of this device preset, used for lookup
name = "adafruit_mpl3115a2"
# Type of this preset; currently the only type is device
type = "device"

# Preset-level metadata; format follows that specified in the top-level
[metadata]
name_full = "Adafruit MPL3115A2 Temp and Pressure Sensor"
author = "C.A.M. Gerlach"
description = "Device preset for reading the Adafruit MPL3115A2 I2C/SPI Temperature/Pressure sensor"
homepage = "https://www.Gerlach.CAM"
repo = "https://github.com/CAM-Gerlach"
preset_version = "0.1.0"
brokkr_version_min = "0.3.0"

# Data types referenced in individual presets
[data_types]
mpl3115a2_temperature = { full_name = "Temperature (MPL3115A2)", binary_type = "f", unit = "C", uncertainty = 3.0, custom_attrs.attribute_name = "temperature", digits = 3, range_min = -40, range_max = 85 }
mpl3115a2_pressure = { full_name = "Pressure (MPL3115A2)", binary_type = "f", unit = "hPa", uncertainty = 0.4, custom_attrs.attribute_name = "pressure", digits = 3, range_min = 200, range_max = 1100 }

# Adafruit MPL3115A2 I2C input
[inputs.mpl3115a2]
_module_path = "brokkr.inputs.adafruiti2c"
_class_name = "AdafruitI2CInput"
# Dependencies required by this specific input preset
_dependencies = [ "adafruit-circuitpython-mpl3115a2" ]
name = "MPL3115A2 I2C Temp & Pressure Sensor"
sensor_module = "adafruit_mpl3115a2"
sensor_class = "MPL3115A2"
data_types = [
    "mpl3115a2_temperature",
    "mpl3115a2_pressure",
]
