config_version = 1
# Name of this device preset, used for lookup
name = "adafruit_bme280"
# Type of this preset; currently the only type is device
type = "device"

# Preset-level metadata; format follows that specified in the top-level
[metadata]
name_full = "Adafruit BME280 Temp/Pressure/Humidity Sensor"
author = "C.A.M. Gerlach"
description = "Device preset for reading the Adafruit BME280 I2C/SPI Temperature/Pressure/Humidity sensor"
homepage = "https://www.Gerlach.CAM"
repo = "https://github.com/CAM-Gerlach"
preset_version = "0.1.0"
brokkr_version_min = "0.3.0"

# Data types referenced in individual presets
[data_types]
bme280_temperature = { full_name = "Temperature (BME280)", binary_type = "f", unit = "C", uncertainty = 1.0, custom_attrs.attribute_name = "temperature", digits = 3, range_min = 0, range_max = 65 }
bme280_pressure = { full_name = "Pressure (BME280)", binary_type = "f", unit = "hPa", uncertainty = 1.0, custom_attrs.attribute_name = "pressure", digits = 3, range_min = 300, range_max = 1100 }
bme280_humidity = { full_name = "Humidity (BME280)", binary_type = "f", unit = "%", uncertainty = 3.0, custom_attrs.attribute_name = "humidity", digits = 3, range_min = 10, range_max = 90 }

# Adafruit BME280 I2C input
[inputs.bme280_i2c]
_module_path = "brokkr.inputs.adafruiti2c"
_class_name = "AdafruitI2CInput"
# Dependencies required by this specific input preset
_dependencies = [ "adafruit-circuitpython-bme280" ]
name = "Adafruit BME280 I2C Temp/Pressure/Humidity Sensor"
sensor_module = "adafruit_bme280"
sensor_class = "Adafruit_BME280_I2C"
data_types = [
    "bme280_temperature",
    "bme280_pressure",
    "bme280_humidity",
]
