config_version = 1
# Name of this device preset, used for lookup
name = "meter_ech2o"
# Type of this preset; currently the only type is device
type = "device"

# Preset-level metadata; format follows that specified in the top-level
[metadata]
name_full = "Meter ECH2O Soil Moisture Sensors"
author = "C.A.M. Gerlach"
description = "Device preset for reading the Meter (Decagon) ECH2O analog soil moisture sensors (EC-5, -10 and -20)"
homepage = "https://www.Gerlach.CAM"
repo = "https://github.com/CAM-Gerlach"
preset_version = "0.1.0"
brokkr_version_min = "0.3.0"

[type_presets]
ech2o_soil_moisture = { conversion = "custom", binary_type = "f", unit = "m^3/m^3", custom_attrs.attribute_name = "voltage", digits = 4 }

# Data types referenced in individual presets
[data_types]
ech2o_ec5_soil_moisture = { type_presets = "ech2o_soil_moisture", full_name = "Soil Moisture (EC-5)", scale = 1.19, offset = -0.400, uncertainty = 0.03, range_min = 0, range_max = 1.0 }
ech2o_ec10_soil_moisture = { type_presets = "ech2o_soil_moisture", full_name = "Soil Moisture (EC-10)", scale = 0.93, offset = -0.376, uncertainty = 0.04, range_min = 0, range_max = 0.4 }
ech2o_ec20_soil_moisture = { type_presets = "ech2o_soil_moisture", full_name = "Soil Moisture (EC-20)", scale = 0.69, offset = -0.290, uncertainty = 0.04, range_min = 0, range_max = 0.4 }

[inputs.ec5_ads1015]
_module_path = "brokkr.inputs.adafruitadc"
_class_name = "AdafruitADCInput"
# Dependencies required by this specific input preset
_dependencies = [ "adafruit-circuitpython-ads1x15" ]
name = "ECH2O EC-5 Soil Moisture Sensor"
sensor_module = "adafruit_ads1x15.ads1015"
sensor_class = "ADS1015"
data_types = [
    "ech2o_ec5_soil_moisture",
]

[inputs.ec10_ads1015]
_module_path = "brokkr.inputs.adafruitadc"
_class_name = "AdafruitADCInput"
# Dependencies required by this specific input preset
_dependencies = [ "adafruit-circuitpython-ads1x15" ]
name = "ECH2O EC-10 Soil Moisture Sensor"
sensor_module = "adafruit_ads1x15.ads1015"
sensor_class = "ADS1015"
data_types = [
    "ech2o_ec10_soil_moisture",
]

[inputs.ec20_ads1015]
_module_path = "brokkr.inputs.adafruitadc"
_class_name = "AdafruitADCInput"
# Dependencies required by this specific input preset
_dependencies = [ "adafruit-circuitpython-ads1x15" ]
name = "ECH2O EC-20 Soil Moisture Sensor"
sensor_module = "adafruit_ads1x15.ads1015"
sensor_class = "ADS1015"
data_types = [
    "ech2o_ec20_soil_moisture",
]

[inputs.ec5_ads1115]
_module_path = "brokkr.inputs.adafruitadc"
_class_name = "AdafruitADCInput"
# Dependencies required by this specific input preset
_dependencies = [ "adafruit-circuitpython-ads1x15" ]
name = "ECH2O EC-5 Soil Moisture Sensor"
sensor_module = "adafruit_ads1x15.ads1115"
sensor_class = "ADS1115"
data_types = [
    "ech2o_ec5_soil_moisture",
]

[inputs.ec10_ads1115]
_module_path = "brokkr.inputs.adafruitadc"
_class_name = "AdafruitADCInput"
# Dependencies required by this specific input preset
_dependencies = [ "adafruit-circuitpython-ads1x15" ]
name = "ECH2O EC-10 Soil Moisture Sensor"
sensor_module = "adafruit_ads1x15.ads1115"
sensor_class = "ADS1115"
data_types = [
    "ech2o_ec10_soil_moisture",
]

[inputs.ec20_ads1115]
_module_path = "brokkr.inputs.adafruitadc"
_class_name = "AdafruitADCInput"
# Dependencies required by this specific input preset
_dependencies = [ "adafruit-circuitpython-ads1x15" ]
name = "ECH2O EC-20 Soil Moisture Sensor"
sensor_module = "adafruit_ads1x15.ads1115"
sensor_class = "ADS1115"
data_types = [
    "ech2o_ec20_soil_moisture",
]
