config_version = 1
# Name of this device preset, used for lookup
name = "raingauge_tipb"
# Type of this preset; currently the only type is device
type = "device"
# Dependencies required by all inputs in this preset
_dependencies = [ "gpiozero", "RPi.GPIO" ]

# Preset-level metadata; format follows that specified in the top-level
[metadata]
name_full = "GPIO Tipping Bucket Rain Gauge"
author = "C.A.M. Gerlach"
description = "Device preset for a typical tipping bucket rain gauge, calibrated by default to 0.5 mm/tip"
homepage = "https://www.Gerlach.CAM"
repo = "https://github.com/CAM-Gerlach"
preset_version = "0.1.0"
brokkr_version_min = "0.3.0"

# Data type presets to use for the data types that follow
[type_presets]
rain_rate = { conversion = "custom", binary_type = "f", scale = 1829, unit = "mm/h", uncertainty = 0.5, digits = 2, range_min = 0, custom_attrs.mean = true }

# Data types referenced in individual presets
[data_types]
tip_count_tipb = { full_name = "Tipping Bucket Count", conversion = "int", binary_type = "i", unit = "", uncertainty = 1, custom_attrs.mean = false, range_min = 0 }
rain_rate_tibp = { type_presets = "rain_rate", full_name = "Rain Rate" }
rain_rate_tibp_1minute = { type_presets = "rain_rate", full_name = "Rain Rate (1 min)", custom_attrs.period_s = 60 }
rain_rate_tibp_5minute = { type_presets = "rain_rate", full_name = "Rain Rate (5 min)", custom_attrs.period_s = 300 }
rain_rate_tibp_1hour = { type_presets = "rain_rate", full_name = "Rain Rate (1 h)", custom_attrs.period_s = 3600 }

# Tipping bucket rain gauge input
[inputs.raingauge_tipb]
_module_path = "brokkr.inputs.gpiocounter"
_class_name = "GPIOCounterInput"
_dependencies = []
name = "Tipping Bucket Rain Gauge"
max_counts = 100000
gpio_kwargs.pull_up = true
gpio_kwargs.bounce_time = 0.025
reset_after_read = true
data_types = [
    "rain_rate_tibp",
]
